# Generated by Django 4.2.30 on 2026-05-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destino", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ciudad",
            old_name="nome",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="estado",
            old_name="nome",
            new_name="nombre",
        ),
    ]
