# Generated by Django 4.2.30 on 2026-05-13 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destino", "0002_rename_nome_ciudad_nombre_rename_nome_estado_nombre"),
        ("lugar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visita",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lugar",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lugar.categoria"
            ),
        ),
        migrations.AddField(
            model_name="lugar",
            name="destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="destino.destino"
            ),
        ),
    ]
